node {
    stage('init'){	
        git 'https://github.com/abola/devops-lab-sample.git'	
    }
    stage('build'){
        sh 'cd sample/pipeline-as-code && mvn package'
    }
    stage('exec'){
        sh 'cd sample/pipeline-as-code && java -cp target/hello-1.0.jar com.systex.HelloWorld'
    }
}
