pipeline {
    agent any
    
    parameters {
        string(description: 'GCP Project Name', name: 'googleProjectId', defaultValue: '')
        password(description: 'GCR credential(gcloud auth print-access-token)', name: 'gcrCredentials', defaultValue: '')
        string(description: 'Docker version build tag', name: 'buildTag', defaultValue: '1.0')
        string(description: '[Helm] backend-java replicas', name: 'backendJavaReplicas', defaultValue: '2')
        string(description: '[Helm] backend-php replicas', name: 'backendPhpReplicas', defaultValue: '2')
        choice(description: '', name: 'stage', choices: ['ci','cd']) 
    }
    
    stages {
        stage('init'){
            steps{
                checkout scm
            }
        }
    
        stage('ci'){
            when {
                expression { params.stage == 'ci' }
            }
            steps{
                // build with tools and build docker image
                sh "cd sample/iac/frontend-python && docker build -t gcr.io/${params.googleProjectId}/frontend-python:$BUILD_TAG ."
                sh "cd sample/iac/backend-java && mvn -Dmaven.test.skip=true package && docker build -t gcr.io/${params.googleProjectId}/backend-java:$BUILD_TAG ."
                sh "cd sample/iac/backend-php && docker build -t gcr.io/${params.googleProjectId}/backend-php:$BUILD_TAG ."
                // show current docker images 
                sh "docker images"
                // add real version tag
                sh "docker tag gcr.io/${params.googleProjectId}/backend-java:$BUILD_TAG gcr.io/${params.googleProjectId}/backend-java:${params.buildTag}"
                sh "docker tag gcr.io/${params.googleProjectId}/backend-php:$BUILD_TAG gcr.io/${params.googleProjectId}/backend-php:${params.buildTag}"
                sh "docker tag gcr.io/${params.googleProjectId}/frontend-python:$BUILD_TAG gcr.io/${params.googleProjectId}/frontend-python:${params.buildTag}"
                // add tag latest
                sh "docker tag gcr.io/${params.googleProjectId}/backend-java:$BUILD_TAG gcr.io/${params.googleProjectId}/backend-java:latest"
                sh "docker tag gcr.io/${params.googleProjectId}/backend-php:$BUILD_TAG gcr.io/${params.googleProjectId}/backend-php:latest"
                sh "docker tag gcr.io/${params.googleProjectId}/frontend-python:$BUILD_TAG gcr.io/${params.googleProjectId}/frontend-python:latest"
                // show current docker images again
                sh "docker images"
                // login GCR 
                sh "docker login -u oauth2accesstoken -p ${params.gcrCredentials} https://gcr.io"
                // push image to GCR
                sh "docker push gcr.io/${params.googleProjectId}/backend-java:${params.buildTag}"
                sh "docker push gcr.io/${params.googleProjectId}/backend-php:${params.buildTag}"
                sh "docker push gcr.io/${params.googleProjectId}/frontend-python:${params.buildTag}"
                sh "docker push gcr.io/${params.googleProjectId}/backend-java:latest"
                sh "docker push gcr.io/${params.googleProjectId}/backend-php:latest"
                sh "docker push gcr.io/${params.googleProjectId}/frontend-python:latest"
            }
        }
    
        stage('cd'){
            when {
                expression { params.stage == 'cd' }
            }
            steps{
                sh "helm init && helm template sample/iac/helm --set iac.backendphp.replicas=${params.backendPhpReplicas} --set iac.backendjava.replicas=${params.backendJavaReplicas} --set iac.google.project=${params.googleProjectId} | kubectl apply -f -"
            }
        }
    }
}
